import type { Metadata } from "next";
import Providers from "../store/Providers";
import { Poppins } from "next/font/google";
import "./globals.css";
import GoogleProvider from "./providers/GoogleProvider";
import { ToastContainer, toast } from "react-toastify";
import Common from "./(user)/_components/common";

const fontPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontPoppins.variable} antialiased`}
      >
        <Providers>
          <Common />
          <GoogleProvider>{children}
          </GoogleProvider>
          <ToastContainer
            position="top-right"
            autoClose={1500}
            hideProgressBar={true}
            pauseOnHover
            draggable
            theme="light"
            newestOnTop
          />
        </Providers>
      </body>
    </html>
  );
}
